apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kjg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: wkdlrn/0319back:v1
          ports:
            - containerPort: 8080
